Dev23082023
HiveBeats/Crm pull request #5
Opened 2023-08-24 07:54 UTC by MaximGubanov

2023-08-24 14:56 UTC, HiveBeats requested changes
Отписал по моментам, которые смутили

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Client.Avalonia/Crm.Client.Avalonia.csproj
> +    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0-preview.7.23375.6" />
Это версия из превью, давай опустим до 6.x? Все-таки у нас приложение на .NET 6

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        _connectionString = connectionString ?? "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;";
Давай поправим все это мракобесие с дефолтными коннекшен стрингами? 
Надо сделать нормально, чтобы, эта строка получалась единожды, при регистрации в DI

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +            new Client("Irina Victorovna", "+79455684645"),
Раз у нас уже есть тестовая БД с данными, в этом нет необходимости

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        _connectionString = "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;";
См поинт про коннекшен стринги

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        optionsBuilder.UseNpgsql(_connectionString ?? "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;", sqlOpt => sqlOpt.CommandTimeout(500));
См поинт про коннекшен стринги

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        optionsBuilder.UseNpgsql("Host=localhost;Username=john;Password=passw0rd;Database=todosdb;");
См поинт про коннекшен стринги

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Server.Infrastructure.Database/ServiceConfiguration.cs
> +public static class ServicesConfiguration
Почему название класса не совпадает с названием файла?

2023-08-24 14:56 UTC, HiveBeats commented on Crm.Server.Infrastructure.Database/ServiceConfiguration.cs
> +    public static void AddCrmServerService(this IServiceCollection services)
Я бы переименовал на что-то менее общее. Это, все-же, не сервис црм-сервера. Это скорее ServerDatabase

2023-08-25 05:28 UTC, MaximGubanov commented on Crm.Client.Avalonia/Crm.Client.Avalonia.csproj
> +    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0-preview.7.23375.6" />
Исправил до версии 6.0.1

2023-08-25 05:40 UTC, MaximGubanov commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +            new Client("Irina Victorovna", "+79455684645"),
удалил

2023-08-25 05:44 UTC, MaximGubanov commented on Crm.Server.Infrastructure.Database/ServiceConfiguration.cs
> +public static class ServicesConfiguration
исправил

2023-08-25 05:46 UTC, MaximGubanov commented on Crm.Server.Infrastructure.Database/ServiceConfiguration.cs
> +    public static void AddCrmServerService(this IServiceCollection services)
Переименовал

2023-08-25 08:37 UTC, MaximGubanov commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        optionsBuilder.UseNpgsql(_connectionString ?? "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;", sqlOpt => sqlOpt.CommandTimeout(500));
+

2023-08-25 08:37 UTC, MaximGubanov commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        optionsBuilder.UseNpgsql("Host=localhost;Username=john;Password=passw0rd;Database=todosdb;");
+

2023-08-25 08:37 UTC, MaximGubanov commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        _connectionString = "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;";
+

2023-08-25 08:38 UTC, MaximGubanov commented on Crm.Server.Infrastructure.Database/CrmDbContext.cs
> +        _connectionString = connectionString ?? "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;";
Внедрил ConnectionString через DI

2023-08-25 11:08 UTC, HiveBeats requested changes
Оставил замечания

2023-08-25 11:08 UTC, HiveBeats commented on Crm.Client.Avalonia/Crm.Client.Avalonia.csproj
Установи appsettings.json чтобы он всегда копировался при билде
`<ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>`

2023-08-25 11:08 UTC, HiveBeats commented on Crm.Client.Avalonia/appsettings.json
> +  "exclude": [
Что это? Какую функцию выполняет и зачем нам?

2023-08-25 11:08 UTC, HiveBeats commented on Crm.Client.Avalonia/appsettings.json
> +  "ConnectionString": "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;",
Коннекшн стринги указываются в виде словаря ключ-значение
```
"ConnectionStrings": {
"MyConnectionName1":"string",
"MyConnectionName2":"string2"
}
```

Обрати внимание, что, написано ConnectionStrings с s на конце. Именно в таком формате будет работать метод расширения Configuration.GetConnectionString("MyConnectionName");

2023-08-25 11:08 UTC, HiveBeats commented on Crm.Client.Avalonia/App.axaml.cs
> +        services.AddDatabaseService(Configuration.GetConnectionString("ConnectionString"));
См комментарий в Appsettings

2023-08-25 11:56 UTC, MaximGubanov commented on Crm.Client.Avalonia/appsettings.json
> +  "ConnectionString": "Host=localhost;Username=john;Password=passw0rd;Database=todosdb;",
Исправил. Строку подключения не менял, т.к. не знаю какая она будет в итоге.

2023-08-25 11:57 UTC, MaximGubanov commented on Crm.Client.Avalonia/App.axaml.cs
> +        services.AddDatabaseService(Configuration.GetConnectionString("ConnectionString"));
Исправил

2023-08-25 11:57 UTC, MaximGubanov commented on Crm.Client.Avalonia/appsettings.json
> +  "exclude": [
Удалил лишнее

2023-08-25 11:58 UTC, MaximGubanov commented on Crm.Client.Avalonia/Crm.Client.Avalonia.csproj
Поправил

2023-08-25 12:09 UTC, HiveBeats commented
Аппрув, можно мерджить

2023-08-25 12:48 UTC, HiveBeats approved these changes

2023-08-25 13:02 UTC, merged