Feature/issue 3
HiveBeats/Crm pull request #6
Opened 2023-09-25 17:41 UTC by MaximGubanov

2023-09-25 17:50 UTC, HiveBeats requested changes

2023-09-25 17:50 UTC, HiveBeats commented on Crm.Client.ViewModel/Clients/ClientsViewModel.cs
> +        // ItemsService = Locator.Current.GetService<IClientService>();
Почему только тут закомментировал, где-то еще используется локатор?
Нужно заместить это функционал либо статическим инстансом ServiceProvider, либо иньекцией в конструктор

2023-09-25 17:50 UTC, HiveBeats commented on Crm.Client.Avalonia/App.axaml.cs
> +        services.AddApplicationService();
Почему везде Services а тут Service?)))))

2023-09-25 18:16 UTC, MaximGubanov commented on Crm.Client.Avalonia/App.axaml.cs
> +        services.AddApplicationService();
Исправил

2023-09-25 18:17 UTC, MaximGubanov commented on Crm.Client.ViewModel/Clients/ClientsViewModel.cs
> +        // ItemsService = Locator.Current.GetService<IClientService>();
Исправил

2023-09-25 18:19 UTC, MaximGubanov commented
Исправления

2023-09-25 18:29 UTC, HiveBeats reviewed
LGTM

2023-09-27 19:08 UTC, HiveBeats approved these changes

2023-09-28 06:21 UTC, merged