Feature/issue 3.1
HiveBeats/Crm pull request #8
Opened 2023-09-29 18:23 UTC by MaximGubanov

2023-09-29 18:28 UTC, MaximGubanov commented on Crm.Client.ViewModel/Departments/DepartmentsViewModel.cs
> -
Я сократил эти вызовы, мне кажется не читабельный код из-за таких внедрений

2023-09-29 18:33 UTC, MaximGubanov commented on Crm.Client.ViewModel/Departments/DepartmentsViewModel.cs
>          RxApp.MainThreadScheduler.ScheduleAsync(OnLoaded);
без этой штуки не загружается список добавленных подразделений

2023-09-30 16:50 UTC, HiveBeats commented on Crm.Client.ViewModel/Departments/DepartmentsViewModel.cs
>          RxApp.MainThreadScheduler.ScheduleAsync(OnLoaded);
без этой - без какой?
пока что, не вижу связи

2023-09-30 17:02 UTC, HiveBeats requested changes

2023-09-30 17:02 UTC, HiveBeats commented on Crm.Client.Application/Departments/DepartmentsService.cs
> +    public DepartmentsService(CrmDbContext db) => _db = db;
Так лучше не делай
скорее всего, впоследствии, придется добавлять что-то еще в конструктор и придется снова ставить эти скобочки
Мелочь, а неприятно

2023-09-30 17:02 UTC, HiveBeats commented on Crm.Client.Avalonia/Views/Clients/ClientsView.axaml
Старайся не совмещать коммиты, делающие что-то одно
С коммитами, которые просто правят идентацию кода и прочее
Потом трудно отслеживать реально значащие изменения в истории

Сделал какие-то правки, функционал - закоммитил. Отдельным коммитом можно потом идентацию и прочее поправить

2023-09-30 17:02 UTC, HiveBeats commented on Crm.Client.ViewModel/Departments/CreateDepartmentViewModel.cs
> +public partial class CreateDepartmentViewModel : ViewModelBase, IModalDialogViewModel, ICloseable
почему Partial?
какая причина для этого?

где-то есть еще часть реализации класса?

2023-09-30 17:02 UTC, HiveBeats commented on Crm.Client.ViewModel/Departments/CreateDepartmentViewModel.cs
> +    public void Cancel()
Не обязательно:
Давай, может, сделаем базовую DialogViewModel?
Которая будет имплементировать методы Ok и Cancel, но останется возможность переопределить в классе-наследнике

2023-09-30 17:02 UTC, HiveBeats commented on Crm.Client.ViewModel/Departments/DepartmentsViewModel.cs
> +public partial class DepartmentsViewModel : ItemsViewModel<Department>, IPageViewModel
Опять же, почему partial?

2023-10-02 16:30 UTC, HiveBeats requested changes

2023-10-02 16:30 UTC, HiveBeats commented on Crm.Client.ViewModel/Clients/ClientsViewModel.cs
> -            .WhenAnyValue<ClientsViewModel, bool, Domain.Models.Client>(x => x.CurrentItem,
Ищи, как сделать валидацию команды
Пользователю вообще не должна быть доступна кнопка совершения действия, если не выполнены условия для ее исполнения

2023-10-02 16:30 UTC, HiveBeats commented on Crm.Client.ViewModel/Clients/CreateClientOrderViewModel.cs
> -		_nameValidation = this.WhenAnyValue(x => x.Name, name => !string.IsNullOrWhiteSpace(name));
Также, валидация

2023-10-03 09:33 UTC, HiveBeats commented
От меня ок, можно мерджить

2023-10-03 09:50 UTC, merged